blank_issues_enabled: false
contact_links:
  - name: "ğŸ™‹â€â™€ï¸ Question"
    url: https://github.com/orgs/foxglove/discussions/new/choose
    about: Search discussions or ask our community for help
  - name: "ğŸš€ Feature request"
    url: https://github.com/orgs/foxglove/discussions/new/choose
    about: Search existing feature requests or share a new idea
  - name: "ğŸ“š Stack Exchange"
    url: https://robotics.stackexchange.com/questions/ask
    about: Get help from the robotics community
  - name: "ğŸ’¬ Live chat"
    url: https://foxglove.dev/slack
    about: Join the discussion in our Slack community
